### ISSUE TITLE
TypeError within Docker-Container

### ISSUE THREAD

**Issue by gklasen** [mysocketio/mysocketctl#9] opened 2020-12-02 19:26 UTC
Thanks for the good work, firstly. =)

Unfortunately, still have following error within Docker environment:

```
Logged in! Token stored in /root/.mysocketio_token

+--------------------------------------+--------------------------------------+---------+------+-----------------+
|              socket_id               |               dns_name               | port(s) | type |       name      |
+--------------------------------------+--------------------------------------+---------+------+-----------------+
| 8633277c-a501-4aad-99e0-8829e85f256c | patient-violet-2814.edge.mysocket.io |  80 443 | http | my test service |
+--------------------------------------+--------------------------------------+---------+------+-----------------+

Connecting to Server: ssh.mysocket.io

Traceback (most recent call last):
  File "/usr/local/bin/mysocketctl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mysocketctl/connect.py", line 84, in connect
    ssh_tunnel(port, remote_bind_port, ssh_server, ssh_user, engine=engine)
  File "/usr/local/lib/python3.6/dist-packages/mysocketctl/utils.py", line 108, in ssh_tunnel
    if ssh().is_enabled():
  File "/usr/local/lib/python3.6/dist-packages/mysocketctl/ssh/system.py", line 10, in is_enabled
    subprocess.run([self.ssh_path, "-V"], capture_output=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

```

**Comment by atoonk** [comment] 2020-12-02 19:30
hi @gklasen  thanks for reporting.
can you share your base dockerfile?

**Comment by atoonk** [comment] 2020-12-02 20:23
I was able to reproduce the issue by running this in a docker container ```docker pull python:3.6.12-slim-buster```

I think I know what the issue is. for now,  you can work around it by using the ```--engine paramiko``` flag. example:
```mysocketctl connect --port 8000 --engine paramiko```

we'll look at getting this fixed properly.
cc @tresni

**Comment by gklasen** [comment] 2020-12-02 20:28
Ahh, just was about to create a smaller example for but. But nice to read to found sth already. Still, maybe this helps as well?

Dockerfile:

```
FROM ubuntu:18.04

MAINTAINER Gerrit Klasen "klasen@XXXX.de"

RUN apt-get update -y && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install python3.8 python3.8-dev python3-pip -y

RUN pip3 install --upgrade pip

#MySocket.io
RUN pip3 install --upgrade mysocketctl
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ARG MYSOCKET_PW=default

# Starting script.
WORKDIR /app
COPY ./start.sh /app/start.sh

RUN chmod +x ./start.sh
CMD [ "./start.sh" ]
```

The shell to start / start.sh:

```
#!/bin/sh

mysocketctl login --email "xxxx@xxxx" --password xxxxx
mysocketctl connect --port 8000 --name "my test service"
```

**Comment by gklasen** [comment] 2020-12-02 20:31
The error has been resolved by using the `--engine paramiko` flag, leading into that one: 

> Couldn't connect No authentication methods available
> Disconnected... Automatically reconnecting now..

Shall i create a new issue on that one?

**Comment by atoonk** [comment] 2020-12-02 20:32
It looks like it maybe related to the fact that ```capture_output``` is new in Python 3.7.
you were using 3.6. so that would explain it. so it seems if you use 3.7 or higher it will work for now,
can you confirm it works with 3.8 above?

**Comment by atoonk** [comment] 2020-12-02 20:33
> Couldn't connect No authentication methods available
> Disconnected... Automatically reconnecting now..

this typically means it can't authenticate you, probably because you don't have the private key in your container?

**Comment by gklasen** [comment] 2020-12-02 20:52
Where within the container it needs to be stored? Copied it to root-folder, where the login-token is present as well.

**Comment by atoonk** [comment] 2020-12-02 20:59
should be in the .ssh folder of the user, so depending on what process runs it:
```~/.ssh/id_rsa```
make sure to set the permissions correctly
```sudo chmod 600 ~/.ssh/id_rsa  ```

**Comment by gklasen** [comment] 2020-12-02 21:02
Okay thanks. So first part: I can confirm since python3.7 it is working without paramiko-engine.

**Comment by tresni** [comment] 2020-12-02 21:24
@atoonk  is there a minimum version of python you want to be targeting?  3.6?  If so, I can setup Tox in my testing branch to do checks on 3.6+ to make sure we haven't broken anything even when developing on 3.8

**Comment by atoonk** [comment] 2020-12-02 21:26
> @atoonk is there a minimum version of python you want to be targeting? 3.6? If so, I can setup Tox in my testing branch to do checks on 3.6+ to make sure we haven't broken anything even when developing on 3.8

i'd like to stick to 3.6 and higher.

**Comment by atoonk** [comment] 2020-12-02 21:27
suggested fix for this
```
--- a/mysocketctl/ssh/system.py
+++ b/mysocketctl/ssh/system.py
@@ -7,7 +7,8 @@ class SystemSSH(object):

     def is_enabled(self):
         try:
-            subprocess.run([self.ssh_path, "-V"], capture_output=True)
+            subprocess.run([self.ssh_path, "-V"],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
```

**Comment by gklasen** [comment] 2020-12-02 21:46
Did the key-copying, now getting:

> 1361a1d22cfe46069ff4379f52e3b233@ssh.mysocket.io: Permission denied (publickey).
> Disconnected... Automatically reconnecting now..

**Comment by atoonk** [comment] 2020-12-02 21:59
hhm that seems to indicate that perhaps that an incorrect key?  are you sure this is the right key?

**Comment by gklasen** [comment] 2020-12-02 22:07
Yes, sorry... `mysocketctl account show` and looking into the key itsself: gave the same.

**Comment by atoonk** [comment] 2020-12-02 22:23
@gklasen  sorry, just need to clarify: 
did you get it to work now? or you see issues still, even when you do ```mysocketctl account show``` ?

**Comment by gklasen** [comment] 2020-12-02 22:26
I got it working, just created another account. only difference: "--ssh-key" path given was the standard one. 
First not working account had another path.

**Comment by atoonk** [comment] 2020-12-02 22:28
Awesome!  happy building!  
let us know when you have something you can share :)

**Comment by atoonk** [comment] 2020-12-03 00:29
mysocketctl 0.7 deployed with this fix

**Closed as completed by atoonk** 2020-12-03 00:29 UTC
